### ISSUE TITLE
Provide blocks of levels

### ISSUE THREAD

**Issue by vasina** [JetBrains/programmer-games#12]
Make the following blocks:
1) Head movement and addition balls at the end of input word
2) Writing the sequence of balls on the tape
3) Balls replacement in the input word ("in place")
4) Characters analysis and comparison (by the transition to different states)
5) Characters deletion and insertion (by word compression and extension)
6) Result formation on the new place on the tape (as alternative of word modification "in place")
7) Fix tape position by using helper characters
8) Tasks with two variants of answer ?

**Comment by mariyadavydova** [comment]
All puzzles from these blocks should be covered by unit-tests.

**Comment by vasina** [comment]
Task about tests in  "Update unit tests for turing machine #17 " issue

**Comment by vasina** [comment]
Implemented at 45e43d1

**Comment by vasina** [comment]
Without  8) Tasks with two variants of answer
Merge 6) Result formation on the new place on the tape (as alternative of word modification "in place")
           7) Fix tape position by using helper characters
