### ISSUE TITLE
Provide unit tests for the Turing Machine implementation from #2

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/programmer-games#3]
At least the following cases should be tested:
1. Add same item (`_ _ 0 _ _` -> `_ _ 0 0 _`)
2. Change item (`_ _ 0 _ _` -> `_ _ 1 _ _`)
3. Replace items (`_ _ 0 1 _` -> `_ _ 1 0 _`)
4. Change one last item (`_ 0 0 0 _` -> `_ 0 0 1 _`)
5. Change each second item (`_ 0 0 0 0 _` -> `_ 0 1 0 1 _`)
6. Replace all items with one item type (`_ 1 2 3 _` -> `_ 0 0 0 _`)

**Comment by vasina** [comment]
Implemented at 3a47f82
