### ISSUE TITLE
Update Turing Machine implementation

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/programmer-games#5]
Instead of working with `comparable` on tape the machine should work with `Maybe comparable`, where Nothing encodes the empty cell on tape.

**Comment by vasina** [comment]
Second implementation of Turing module with List (Maybe a) input with small fix (Array.empty instead of Array.FromList [Nothing] in initTapeCfg) - 5a59113. First impl. in issue ( Replace a function with a table in Turing Machine #7 )
