### ISSUE TITLE
Replace a function with a table in Turing Machine

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/programmer-games#7]
Instead of taking a function denoting the actions based on current state and character, Turing runner should operate with a table of movements (most likely it should be a map or a map of maps).

`(Kitten.Grey, Ball.Yellow) -> (Ball.Red, Kitten.Black, Move.Right)`

**Comment by vasina** [comment]
Implemetation without Maybe new symb -  ef055fc

**Comment by vasina** [comment]
First implementation with List (Maybe a) as an input - 6d46328

**Comment by vasina** [comment]
Second implementation with small fix (Array.empty instead of Array.FromList [Nothing] in initTapeCfg) -  5a59113
